name: CI/CD build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Main branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven and deploy to Artifactory
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: mvn -s settings.xml --batch-mode --update-snapshots deploy

      - name: Generate Java docs
        run: mvn javadoc:aggregate

      - name: Generate Reference docs
        working-directory: spring-batch-docs
        run: mvn site

      - name: Capture project version
        run: echo PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version --quiet -DforceStdout) >> $GITHUB_ENV

      - name: Deploy docs
        env:
          DOCS_HOST: ${{ secrets.DOCS_HOST }}
          DOCS_PATH: ${{ secrets.DOCS_PATH }}
          DOCS_SSH_KEY: ${{ secrets.DOCS_SSH_KEY }}
        working-directory: spring-batch-docs
        run: |
          cd target && unzip spring-batch-$PROJECT_VERSION-docs.zip && \
          scp -i $DOCS_SSH_KEY -r api $DOCS_HOST:$DOCS_PATH/$PROJECT_VERSION && \
          scp -i $DOCS_SSH_KEY -r reference $DOCS_HOST:$DOCS_PATH/$PROJECT_VERSION
