name: CI/CD build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Main branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Generate Java docs
        run: mvn javadoc:aggregate

      - name: Generate Reference docs
        working-directory: spring-batch-docs
        run: mvn site
